### PR TITLE
Default inner constructor

### PR DESCRIPTION
**Pull request by YingboMa**

### CODE REVIEW

**Review by ChrisRackauckas — APPROVED** [review]

**Comment by sunoru** [comment]
Hi, thanks for the pr, but I'm sorry I couldn't get what this inner constructor is for... Doesn't it make all `Xoroshiro128(x, y)` calls from outside a `Xoroshiro128(0, 0)`?

**Comment by YingboMa** [comment]
Oh, right. It should be `new(x, y)`, shouldn't it.

**Comment by sunoru** [comment]
Yeah. Why is this necessary?

**Comment by YingboMa** [comment]
So it's copy-paste-able from the printing
```julia
julia> Xorshifts.Xoroshiro128()
RandomNumbers.Xorshifts.Xoroshiro128(0x862c413b9d2f217c, 0x5ce0ec59c094162b)

julia> RandomNumbers.Xorshifts.Xoroshiro128(0x862c413b9d2f217c, 0x5ce0ec59c094162b)
RandomNumbers.Xorshifts.Xoroshiro128(0x862c413b9d2f217c, 0x5ce0ec59c094162b)
```

**Comment by ChrisRackauckas** [comment]
It's a standard across Julia for 2-argument show methods to be round-trippable.

**Comment by sunoru** [comment]
Oh I see, I didn't realize this method is not automatically generated.

**Comment by ChrisRackauckas** [comment]
Could this please get a tag?

**Pull request merged**
